# Generated by Django 5.0 on 2023-12-30 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urna", "0003_alter_candidato_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="numero",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Número",
            ),
        ),
    ]
